spring:
  application:
    name: coreapi-communications
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DB:coreapi_communications}
    username: ${DB_USER:coreapi_communications}
    password: ${DB_PASSWORD:coreapi_communications}
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 580000
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        query:
          plan_cache_max_size: 64
          in_clause_parameter_padding: true
    open-in-view: false
  flyway:
    baseline-on-migrate: true
    placeholder-prefix: $$
  internal:
    tasks:
      send-email:
        enables: true
        initial-delay: 2000
        rate: 5000