name: Java CI with Maven
env:
  JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.11-9/x64
  JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.11-9/x64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: coreapi_auth
          POSTGRES_PASSWORD: coreapi_auth
          POSTGRES_DB: coreapi_auth
        options: >-
          --health-cmd "pg_isready -U $POSTGRES_USER"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo '<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ secrets.USERNAME_GITHUB }}</username>
                      <password>${{ secrets.TOKEN_GITHUB }}</password>
                    </server>
                  </servers>
                </settings>' > ~/.m2/settings.xml

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml --settings ~/.m2/settings.xml

  spotless_check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo '<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ secrets.USERNAME_GITHUB }}</username>
                      <password>${{ secrets.TOKEN_GITHUB }}</password>
                    </server>
                  </servers>
                </settings>' > ~/.m2/settings.xml

      - name: Run spotless check
        run: mvn spotless:check --settings ~/.m2/settings.xml 
        
  spotbugs_check:
     runs-on: ubuntu-latest
     needs: build
     steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo '<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ secrets.USERNAME_GITHUB }}</username>
                      <password>${{ secrets.TOKEN_GITHUB }}</password>
                    </server>
                  </servers>
                </settings>' > ~/.m2/settings.xml

      - name: Run spotless check
        run: mvn spotbugs:check --settings ~/.m2/settings.xml
